### PR TITLE
avoid running plugin tests on forked PRs

### PR DESCRIPTION
**Pull request by pixelb**
As per https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/

### CODE REVIEW

**Comment by pixelb** [comment]
I've confirmed that this does not run circleci_pipeline.py on this PR based on a separate repo,
and does run it on a PR froma branch on the main repo

**Comment by jieru-hu** [comment]
How about we skip ray launcher tests only? IMHO it is still valuable to run tests on other plugins for forked PR since we do see more external contributions for some of them.
if that makes sense, we can modify this script https://github.com/facebookresearch/hydra/blob/main/tools/ci/circleci_pipeline.py instead of the circle CI yaml?

**Comment by pixelb** [comment]
Two issues with that I see.
- We still make ci token available in environment.
- We still make aws tokens available in environment for non ray plugins
I'm not sure we can effectively remove env vars programatically

**Comment by pixelb** [comment]
github seems to be linking the wrong tests for this pr (using the local repo branch name instead).

The correct tests are: https://app.circleci.com/pipelines/github/facebookresearch/hydra?branch=pull%2F2180&filter=all

**Review by jieru-hu — APPROVED** [review]
thanks!
per our offline discussions, we will look into adding the rest of the plugin tests directly into `config.yml` instead of from calling the API (to avoid exposing the other tokens.)

**Comment by pixelb** [comment]
> thanks! per our offline discussions, we will look into adding the rest of the plugin tests directly into `config.yml` instead of from calling the API (to avoid exposing the other tokens.)

Follow up in issue #2181

**Pull request merged**
