### PR TITLE
Fix indents

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

I found some tiny indent problem in the document, so, I create this PR to fix them.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

Not necessary

## Related Issues and PRs

Nothing

### CODE REVIEW

**Review by omry — CHANGES_REQUESTED** [review]
Thanks. can you also update in the 1.0 version directory? (you can run the local server to check the results).

**Comment by nzw0301** [comment]
@omry Thank you for the quick feedback! I updated the version 1.0 directory.

**Comment by omry** [comment]
Please rebase and try again, I suspect a recent update of OmegaConf is causing the tests to fail.

**Review by omry — APPROVED** [review]
Great, thanks.

**Comment by nzw0301** [comment]
It's my pleasure. Thank you for your reviewing!

**Pull request merged**
