### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by andrewjong**
Fix typo: "dafault" --> "default"

## Motivation

English spelling

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

Read it, common knowledge of the spelling "default".

## Related Issues and PRs

None

### CODE REVIEW

**Comment by omry** [comment]
Whoops, nice catch.

**Comment by omry** [comment]
Hehe, @andrewjong - oops, shouldn't have merged it so quickly :)

Do you mind signing that CLA?

**Comment by andrewjong** [comment]
Done!

**Comment by omry** [comment]
awesome, thanks!

**Pull request merged**
