### PR TITLE
fix nevergrad warning

### LINKED ISSUE #1684: CI fails with UserWarning raised from importing nevergrad
example failure here https://app.circleci.com/pipelines/github/facebookresearch/hydra/10584/workflows/d4c57363-bb31-42f4-a7ee-29c28a577f67/jobs/95695

this can be reproduced by simply importing nevergrad
```
>>> import nevergrad as ng
/Users/jieru/opt/anaconda3/envs/testnv/lib/python3.8/site-packages/cma/s.py:13: UserWarning: Could not import matplotlib.pyplot, therefore ``cma.plot()`` etc. is not available
  _warnings.warn('Could not import matplotlib.pyplot, therefore'
```

the warnings comes from one of nevergrad's dependency `cma` which just had a new release https://github.com/CMA-ES/pycma/releases

### PR DESCRIPTION
**Pull request by jieru-hu**
Closes #1684

### CODE REVIEW

**Comment by omry** [comment]
Is this something that should be fixed upstream?
If so, can we fix it by pinning to a specific version of nevergrad (or a dependency) that works without the warning?

**Comment by jieru-hu** [comment]
> Is this something that should be fixed upstream?
> If so, can we fix it by pinning to a specific version of nevergrad (or a dependency) that works without the warning?

Alternatively, we can:
1) create an issue in `nevergrad` to ask them to pin to `cma==3.0.3` 
and/or 2) pin to that version in nevergrad sweeper ourselves.

This warning only get issued when `matplotlib` is not installed - I think it makes more sense for us to filter it during testing.

**Comment by omry** [comment]
I think as an immediate fix for the CI issues, we should just pin cma to 3.0.3 until we figure out if Nevergrad plans to address this somehow.

@jrapin, any advice here?

**Comment by jieru-hu** [comment]
> I think as an immediate fix for the CI issues, we should just pin cma to 3.0.3 until we figure out if Nevergrad plans to address this somehow.
> 
> @jrapin, any advice here?

OK. for now, I will create an issue in nevergrad and update this PR.

**Comment by jieru-hu** [comment]
filed https://github.com/facebookresearch/nevergrad/issues/1160

**Comment by jieru-hu** [comment]
the nevergrad warning is fixed, the rest of the two tests failed from a pip deprecation warnings #1687

@omry let's land this first and then fix #1687?

**Comment by omry** [comment]
Go ahead and land this, but I don't think the failure is because the deprecation warning.
```
$ pip install plugins/hydra_nevergrad_sweeper/ && echo === Exit code $?
Processing ./plugins/hydra_nevergrad_sweeper
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy<1.20.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from hydra-nevergrad-sweeper==1.1.5) (1.19.5)
Requirement already satisfied: hydra-core>=1.1.0.dev7 in /Users/omry/dev/hydra (from hydra-nevergrad-sweeper==1.1.5) (1.1.0)
Requirement already satisfied: nevergrad>=0.4.3.post2 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from hydra-nevergrad-sweeper==1.1.5) (0.4.3.post3)
Requirement already satisfied: omegaconf==2.1.* in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from hydra-core>=1.1.0.dev7->hydra-nevergrad-sweeper==1.1.5) (2.1.0)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from hydra-core>=1.1.0.dev7->hydra-nevergrad-sweeper==1.1.5) (4.8)
Requirement already satisfied: importlib-resources in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from hydra-core>=1.1.0.dev7->hydra-nevergrad-sweeper==1.1.5) (5.1.0)
Requirement already satisfied: PyYAML>=5.1.* in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from omegaconf==2.1.*->hydra-core>=1.1.0.dev7->hydra-nevergrad-sweeper==1.1.5) (5.4.1)
Requirement already satisfied: cma>=2.6.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (3.0.3)
Requirement already satisfied: bayesian-optimization>=1.2.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (1.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (3.7.4.3)
Requirement already satisfied: scipy>=0.14.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from bayesian-optimization>=1.2.0->nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (1.6.3)
Requirement already satisfied: scikit-learn>=0.18.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from bayesian-optimization>=1.2.0->nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (0.24.2)
Requirement already satisfied: joblib>=0.11 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/omry/miniconda3/envs/hydra38/lib/python3.8/site-packages (from scikit-learn>=0.18.0->bayesian-optimization>=1.2.0->nevergrad>=0.4.3.post2->hydra-nevergrad-sweeper==1.1.5) (2.1.0)
Building wheels for collected packages: hydra-nevergrad-sweeper
  Building wheel for hydra-nevergrad-sweeper (PEP 517) ... done
  Created wheel for hydra-nevergrad-sweeper: filename=hydra_nevergrad_sweeper-1.1.5-py3-none-any.whl size=6156 sha256=15b1f12f2bf1aa354ec5b249b3cbb0d420dbfca2aae3ca6b8f0e0a2662a6b226
  Stored in directory: /private/var/folders/fm/67k5__6x6bq1yz53_g9n4f340000gn/T/pip-ephem-wheel-cache-h3qmianc/wheels/f3/7e/50/4e35f05087781a9eb8f3ba46ddb50ee804db5ce5635d3f8311
Successfully built hydra-nevergrad-sweeper
Installing collected packages: hydra-nevergrad-sweeper
  Attempting uninstall: hydra-nevergrad-sweeper
    Found existing installation: hydra-nevergrad-sweeper 1.1.5
    Uninstalling hydra-nevergrad-sweeper-1.1.5:
      Successfully uninstalled hydra-nevergrad-sweeper-1.1.5
Successfully installed hydra-nevergrad-sweeper-1.1.5
=== Exit code 0
```

**Comment by jieru-hu** [comment]
@omry you are right  - I got myself confused there... I also cannot repro the failure locally, not sure if it's intermittent. will keep looking

**Comment by omry** [comment]
I have seen this last week. This is what @Jasha10 was trying to solve.

Ideas:
1. Maybe it is related to the deprecation, does it go away if we use the suggested command in CI?
2. Maybe it's related to pytorch 1.9, does it go away if we pin to 1.8?
3. Can you repro by sshing into the failing machine?
4. At some point, I think I saw something online about -9 being related to a memory issue. I can't find it now.
Maybe the newer version of pytorch requires too much memory to install for some reason.
Does it go away if we use a bigger linux machine? (using this as the fix should be last resort).

**Pull request merged**
