### PR TITLE
update hydra.runtime.choices during multirun

### LINKED ISSUE #1882: [Bug?] hydra.runtime.choices seems not to reflect current choice during multi-run
# 🐛 Bug
## Description

config value `${hydra:runtime.choices}` seems not to reflect current choice under multi-run settings.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
For simple reproduction, I prepared a set of files with the following directory structure.
```
src/
├── config
│   ├── config.yaml
│   └── option
│       ├── option1.yaml
│       └── option2.yaml
└── main.py
```

The contents of the files are described below.
* `src/config/config.yaml`
```yaml
defaults:
  - option: option1
  - _self_
selected_option: ${hydra:runtime.choices.option}
overriden_values: ${hydra:overrides}
```
* `src/config/option/option1.yaml`
```yaml
value: value1
```

* `src/config/option/option2.yaml`
```yaml
value: value2
```

* `src/main.py`
```python
import hydra

@hydra.main(config_path="config", config_name="config")
def main(config):
    print(f"option name: {config.selected_option}.")
    print(f"option value: {config.option.value}")
    print(f"overriden values: {config.overriden_values}")

if __name__ == "__main__":
    main()

```

** Stack trace/error message **
I ran the following multi-run script and got the following logs.
```
python src/main.py -m option=option2,option1
[2021-11-10 09:04:48,546][HYDRA] Launching 2 jobs locally
[2021-11-10 09:04:48,546][HYDRA]        #0 : option=option2
option name: option1.
option value: value2
overriden values: {'hydra': [], 'task': ['option=option2']}
[2021-11-10 09:04:48,605][HYDRA]        #1 : option=option1
option name: option1.
option value: value1
overriden values: {'hydra': [], 'task': ['option=option1']}
```
I expect the value of the config name (`config.selected_options`, retrieved by resolver `${hydra:runtime.choices.option}`) to change with respect to overridden `option` value, as well as `config.overridden_values` does. 
But this value seems not to be changed.

## Expected Behavior

```
python src/main.py -m option=option2,option1
[2021-11-10 09:04:48,546][HYDRA] Launching 2 jobs locally
[2021-11-10 09:04:48,546][HYDRA]        #0 : option=option2
option name: option2.  ## <-- this value is expected to be changed.
option value: value2
overriden values: {'hydra': [], 'task': ['option=option2']}
[2021-11-10 09:04:48,605][HYDRA]        #1 : option=option1
option name: option1.
option value: value1
overriden values: {'hydra': [], 'task': ['option=option1']}
```

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.8.10
- **Virtual environment type and version** :  pipenv, version 2020.11.15
- **Operating system** : Ubuntu 20.04.2 LTS

### PR DESCRIPTION
**Pull request by jieru-hu**
closes #1882 

The particular line of code deleted in this PR is redundant and actually override the correct value to an outdated one.

### CODE REVIEW

**Review by Jasha10 — APPROVED** [review]
Looks good to me!

**Review by pixelb — APPROVED** [review]
👍

**Comment by Jackwaggon33** [comment]
32269cd0ac11e5c08e252acfa33c3e04d1d8220adefaults: 
   - dataset: imagenet 
   - model: alexnet 
   - optional dataset_model: ${dataset}_${model}

**Comment by Jackwaggon33** [comment]
> Https//:www.32269/cdac/- [ ] 11e5c08e252acfa33c3e04d1d822/__defaults:
>    - dataset: imagenet 
>    - model: alexnet 
>    - optional dataset_model: ${dataset}_$# {model}****

**Pull request merged**
