### PR TITLE
Group plugins in the documentation

### PR DESCRIPTION
**Pull request by shagunsodhani**
## Motivation

Group plugins in the documentation.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

CI

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by shagunsodhani** [comment]
Screen Shot 2020-12-02 at 12 06 18 PM
Screen Shot 2020-12-02 at 12 09 42 PM

**Comment by omry** [comment]
Nice!
Let's ungroup colorlog until we have more misc plugins.
I think this would be a reasonable order (It's just accidentally sorted):

- colorlog
- Launchers
- Sweepers

**Comment by shagunsodhani** [comment]
Screen Shot 2020-12-02 at 4 45 27 PM
Screen Shot 2020-12-02 at 4 45 38 PM

**Review by omry — APPROVED** [review]
Thanks!

**Pull request merged**
