### PR TITLE
[Configen] Enable str defaults from signatures without type annotations

### PR DESCRIPTION
**Pull request by romesco**
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

Tests remain the same.

## Related Issues and PRs

Fixes: #1071

### CODE REVIEW

**Review by omry — CHANGES_REQUESTED** [review]
I am not seeing a test covering this. Please add one.

**Comment by romesco** [comment]
> I am not seeing a test covering this. Please add one.

done

**Comment by omry** [comment]
1. You have some lint failures.
2. by the way, did you see the comment at the top of the test?
```python
##
# To re-generate the expected config run the following command from configen's root directory (tools/configen).
#
# PYTHONPATH=. configen --config-dir tests/gen-test-expected/
#
##
```
This can save some time when adding test cases.

**Comment by omry** [comment]
@romesco , fix the CI failures?

**Comment by romesco** [comment]
yep, i'm doing it! found out the command:
`PYTHONPATH=. configen --config-dir tests/gen-test-expected/` was generating the template to compare against in the wrong order which gave me a new test problem.

I also fixed that and it will be included in this PR.

**Comment by romesco** [comment]
all set

**Review by omry — APPROVED** [review]
looking good.

**Pull request merged**
