### PR TITLE
[Submitit] add support for stderr_to_stdout.

### LINKED ISSUE #1967: [Feature Request] submitit: add `stderr_to_stdout` ass supported by submitit
# 🚀 Feature Request

`stderr_to_stdout` option was added in submitit (not the plugin)  [last year](https://github.com/facebookincubator/submitit/pull/1611) but cannot currently be given from submitit plugin. 

We should add support for passing this `stderr_to_stdout`  via the plugin as well.

cc @Jasha10

### PR DESCRIPTION
**Pull request by YannDubs**
closes #1967 

## Motivation

Add support for passing this `stderr_to_stdout` to submitit.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Jasha10** [comment]
Thanks @YannDubs.
I believe that this update will not be compatible with older versions of the `submitit` library. Could you please update the submitit version pin in the [`hydra/plugins/hydra_submitit_launcher/setup.py`](https://github.com/facebookresearch/hydra/blob/a8e247d3b01d04c21ee1b2220737c60b24664221/plugins/hydra_submitit_launcher/setup.py#L29) file?

**Comment by YannDubs** [comment]
Sorry I missed that @Jasha10 . It's now updated to the oldest version that does not break.

**Comment by YannDubs** [comment]
not sure why there's one failing test, it doesn't seem to be related (?)

**Comment by Jasha10** [comment]
It is indeed unrelated.

**Review by Jasha10 — APPROVED** [review]

**Review by pixelb — APPROVED** [review]

**Pull request merged**
