### PR TITLE
Fix master -> main references in jupyter_notebooks.md

### PR DESCRIPTION
**Pull request by willprice**
The master branch no longer exists on github, so these links have rotted.
I have updated them with the correct URL.

### CODE REVIEW

**Comment by jieru-hu** [comment]
thank you @willprice 
would you mind updating the versioned doc as well? https://github.com/facebookresearch/hydra/tree/main/website/versioned_docs/version-1.1

**Review by jieru-hu — CHANGES_REQUESTED** [review]
thank you. see my previous comment. :)

**Comment by Jasha10** [comment]
Updated in https://github.com/willprice/hydra/commit/5dd144258910cbb2cd92f0988c51af4644f38b4b.

**Comment by Jasha10** [comment]
@willprice thank you for your contribution.

**Pull request merged**
