### PR TITLE
[Ax Plugin] Delete conf and search path plugin

### PR DESCRIPTION
**Pull request by shagunsodhani**
## Motivation

Related to #469 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

Passes tests

## Related Issues and PRs

#469 #670

### CODE REVIEW

**Comment by omry** [comment]
As far as I can see you are not deleting the config file.

**Comment by shagunsodhani** [comment]
ouch my bad - thank you for spotting it

**Comment by omry** [comment]
So you see, removing the config file actually exposed that you didn't set the minimize flag to True.

Speaking of which:
This IS an opportunity for a an Enum:

```python
class Optimize(Enum):
  minimize = 1
  maximize = 2
```

but we can stick to the Ax API if we want.

**Comment by shagunsodhani** [comment]
> So you see, removing the config file actually exposed that you didn't set the minimize flag to True.
> 
> Speaking of which:
> This IS an opportunity for a an Enum:
> 
> ```python
> class Optimize(Enum):
>   minimize = 1
>   maximize = 2
> ```
> 
> but we can stick to the Ax API if we want.

Lets stick to Ax API for now.

**Comment by shagunsodhani** [comment]
pop()

**Pull request merged**
