### PR TITLE
Add cookies link to the website (#1212)

### PR DESCRIPTION
**Pull request by jieru-hu**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes/No

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by omry** [comment]
Didn't you already did this?

**Comment by jieru-hu** [comment]
> Didn't you already did this?

Thought we should also do this for the internal doc in fbcode?

**Comment by omry** [comment]
> > Didn't you already did this?
> 
> Thought we should also do this for the internal doc in fbcode?

I don't get it.

**Comment by jieru-hu** [comment]
> > > Didn't you already did this?
> > 
> > 
> > Thought we should also do this for the internal doc in fbcode?
> 
> I don't get it.

In fbcode we render the website on 1.0_branch, so I thought this change also applies here.

**Comment by omry** [comment]
I see, that's correct.
however, we don't really need to update this link in the internal website, but sure :).

**Review by omry — APPROVED** [review]

**Pull request merged**
