### PR TITLE
Update hydra_compose_example.py

### PR DESCRIPTION
**Pull request by hrchu**

### CODE REVIEW

**Comment by omry** [comment]
Oh dang, I missed it when I changed the API.
Thanks for fixing it.
There should be a unit test testing that example, can you add one in tests/test_tutorials.py ?

There should be similar tests there testing other examples.

**Comment by omry** [comment]
Great, thanks.
Can you fix the lint issues?
`nox -s lint`

**Comment by omry** [comment]
I also recommend that you add the commit hooks to avoid this in the future, check [this](https://hydra.cc/docs/development/contributing) for more info.

**Comment by hrchu** [comment]
@omry done.

**Comment by omry** [comment]
Awesome, thanks!

**Pull request merged**
