### PR TITLE
typo in config file prevented AxSweeper from loading correctly

### PR DESCRIPTION
**Pull request by dhpollack**
this is a super mini PR.  The config file points to the wrong location.  I bashed my head against the wall for a while trying to figure out what was going wrong.

### CODE REVIEW

**Comment by omry** [comment]
@shagunsodhani, we need a test that covers the example app properly.

**Comment by omry** [comment]
Thanks David!

**Comment by dhpollack** [comment]
Also, it wasn't completely obvious to me, but you could remove that line entirely as long as you have the defaults line loading the sweeper.  It makes sense to override some of the default settings, but it doesn't really ever make sense to override the class itself.

**Comment by omry** [comment]
> Also, it wasn't completely obvious to me, but you could remove that line entirely as long as you have the defaults line loading the sweeper. It makes sense to override some of the default settings, but it doesn't really ever make sense to override the class itself.


Yup, I think there is a standing PR for something else that removes that line already.

**Comment by shagunsodhani** [comment]
Hey @dhpollack Thank you for fixing this :)

**Pull request merged**
