### PR TITLE
Adding new Hydra logo to README

### PR DESCRIPTION
**Pull request by iamdarshshah**
## Motivation
Thought of making README.md more catchy by adding Logo to it. And it's a best practice to have a logo in an Open-Source project.
- [x] Updating Readme.md file by adding the Hydra logo.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

> Screenshot: 
Hydra

### CODE REVIEW

**Comment by omry** [comment]
Awesome, can you show a screen shot?

**Comment by omry** [comment]
Here are two layouts (I like the second one more):
https://excalidraw.com/#room=d361c082c46e3647763f,dSwmpofh1ymAXa5Wf63TzQ (live session ,we can edit together).

There is also an option to go with a background image similar to the FireStats logo [here](firestats.cc).

**Comment by omry** [comment]
I will try to get some designer feedback for the design alternatives in the link.

**Comment by iamdarshshah** [comment]
Sure @omry 👍

**Comment by omry** [comment]
This looks great. I have an unrelated issue with a dependency of one of the plugins. once it's fixed we will be able to rebase this one and land it.

**Pull request merged**
