### PR TITLE
Add qos and gres SLURM parameters

### PR DESCRIPTION
**Pull request by martenlienen**
## Motivation

Just add support for two missing SLURM parameters.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan
Not necessary

## Related Issues and PRs
No

### CODE REVIEW

**Comment by martenlienen** [comment]
It looks like the failing build job had network issues. Is there a way to force a re-run?

**Comment by Jasha10** [comment]
> Is there a way to force a re-run?

Yes, in general you can trigger CI by pushing an empty commit to the branch.

**Comment by martenlienen** [comment]
That worked, thanks. This time there were also no network issues.

**Review by jieru-hu — APPROVED** [review]
lgtm. Thank you!

**Pull request merged**
