### PR TITLE
add 'params' to defaults list of BasicSweeperConf

### PR DESCRIPTION
**Pull request by Jasha10**
This PR adds 'params' group to the defaults list of BasicSweeperConf

This enables the use-case described in [this comment](https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1011081624).

Basically, if you have a file layout like this:
```text
.
├── my_app.py
├── conf
    ├── config.yaml
    └── hydra
        └── sweeper
            └── params
                └── grid_search.yaml
```
it is now possible to run `python my_app.py --multirun hydra/sweeper/params=grid_search`
whereas previously this would have resulted in an error saying that `hydra/sweeper/params`
does not appear in the defaults list.

Related to #1376.

### CODE REVIEW

**Comment by jieru-hu** [comment]
sorry I missed this one (saw it was in draft so didn't review.)  is it ready for review now?

**Comment by Jasha10** [comment]
> sorry I missed this one (saw it was in draft so didn't review.) is it ready for review now?

Yes, it's ready!

**Comment by Jasha10** [comment]
Btw, my [comment here](https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1011704938) mentions two methods to satisfy the same use-case.

Method 2 depends on this PR, and method 1 involves an @package directive. My question is: since method 1 is available, should we even merge this PR?

This PR updates the defaults list for BasicSweeper, but not for the other sweepers. If we merge this, we'd have to do followup PRs for the other sweepers; their defaults lists would need updating in order to keep them consistent.
I'm not sure it's worth the effort given the existing workaround (method 1 mentioned above). Let me know what you think @jieru-hu .

**Comment by jieru-hu** [comment]
Thanks for the context @Jasha10 . Since option1 seems to be perfectly working and also follows the experiment pattern, i'd say let's hold off on this one for now?

**Comment by Jasha10** [comment]
Okey dokey.

**Pull request closed without merging**
