### PR TITLE
Add hydra/grammar/gen/ to gitignore

### PR DESCRIPTION
**Pull request by jieru-hu**
## Motivation
hydra/grammar/gen/ is created after building hydra, I don't want to accidentally commit the change. 

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes/No

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by omry** [comment]
You can use python_version with an optional level:

````python
In [20]: def foo(x : Optional[str] = None):
    ...:     print(x)
    ...: 

In [21]: OmegaConf.register_resolver("foo", foo)

In [22]: OmegaConf.create({"x" : "${foo:}"}).x
None

In [23]: OmegaConf.create({"x" : "${foo:bar}"}).x
bar
```

**Comment by omry** [comment]
Your motivation is recursive.
Is this solving a problem?

**Comment by jieru-hu** [comment]
> Your motivation is recursive.
> Is this solving a problem?

Yea, after I build the new hydra for releasing, hydra/grammar/gen/ is created on my disk, and I don't want to accidentally commit that change.

**Comment by omry** [comment]
It has a .gitignore inside it that will prevent committing if any generated files.

**Comment by jieru-hu** [comment]
> It has a .gitignore inside it that will prevent committing if any generated files.

I'm probably missing some contexts here. Could you clarify what you mean by "it has a .gitignore", what is ```it``` in this context?

**Comment by omry** [comment]
there is a .gitignore in that directory.

**Comment by shagunsodhani** [comment]
I dont think its there:

```
(hydra38) ➜  hydra git:(22022aa9) ✗ ls -alh hydra/grammar/gen/
total 71K
drwxrwxr-x 3 sodhani sodhani    0 Jul 14 15:17 .
drwxrwxr-x 4 sodhani sodhani    0 Jul 14 15:17 ..
-rw-rw-r-- 1 sodhani sodhani 4.9K Jul 15 06:34 Override.interp
-rw-rw-r-- 1 sodhani sodhani 9.3K Jul 15 06:34 OverrideLexer.interp
-rw-rw-r-- 1 sodhani sodhani  11K Jul 15 06:34 OverrideLexer.py
-rw-rw-r-- 1 sodhani sodhani  319 Jul 15 06:34 OverrideLexer.tokens
-rw-rw-r-- 1 sodhani sodhani 3.5K Jul 15 06:34 OverrideListener.py
-rw-rw-r-- 1 sodhani sodhani  39K Jul 15 06:34 OverrideParser.py
-rw-rw-r-- 1 sodhani sodhani  319 Jul 15 06:34 Override.tokens
-rw-rw-r-- 1 sodhani sodhani 2.3K Jul 15 06:34 OverrideVisitor.py
drwxrwxr-x 2 sodhani sodhani    0 Jul 15 10:15 __pycache__
```

Moreover, the directory is shown as `untracked`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	hydra/grammar/gen/
```

**Comment by omry** [comment]
Gotcha.
I was ignoring itself, I will added it in a followup diff. thanks for letting me know :)

**Comment by jieru-hu** [comment]
cool, closing this one per discussion.

**Pull request closed without merging**
