### PR TITLE
Upgrade `antlr` to 4.11

### PR DESCRIPTION
**Pull request by jlopezpena**
## Motivation

PR following up on [this discussion](https://github.com/facebookresearch/hydra/issues/2699) regarding updating `antlr4` binary and runtime to a more recent version.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/main/CONTRIBUTING.md)?

Yes

## Test Plan

Usual tests should suffice, if there is anything broken with the new `antlr` it should fail at processing the grammars at build time

## Related Issues and PRs

In order to merge this PR a new version of `omegaconf` that includes [the corresponding update there](https://github.com/omry/omegaconf/pull/1114) should be released

### CODE REVIEW

**Comment by Jasha10** [comment]
> There are many test failures in CI, but they fail in every single PR so I don't think they are related to my changes

Yup. The core tests are passing, which is certainly a good sign.

**Comment by Jasha10** [comment]
I don't think the behavior is deprecated. Some legacy Hydra behavior is still supported via the version_base setting. I'll take a look at those failures. They certainly do seem unrelated to this pr.

**Review by Jasha10 — APPROVED** [review]
I'm going to move forward with merging this PR and the sister PR https://github.com/omry/omegaconf/pull/1114. The CI failures here are unrelated to the changes from this PR.

**Comment by Jasha10** [comment]
This is looking good except for the python3.7 tests. It looks like omegaconf==2.4.0.dev2 cannot be installed with python3.7. I'm not sure what's causing this, but anyway our options are:

1) troubleshoot the pypi upload so that `pip3.7 install omegaconf==2.4.0.dev2` works, or
2) drop hydra's support for python3.7.

I am biased towards the former option.

**Comment by Jasha10** [comment]
I've submitted PR #2854 to drop support for python3.7.

**Comment by odelalleau** [comment]
> Hi @jlopezpena, it seems is an [unresolved issue](https://app.circleci.com/pipelines/github/facebookresearch/hydra/15579/workflows/891fca0c-161a-4cea-8deb-2b0983fe7475/jobs/160870) in the windows CI job. Do you have any insight about what's going on here?

It says
```
org/antlr/v4/Tool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
which suggests we either need to find a way to upgrade the java version on the Windows machine, or rebuild the `.jar` with an older version.

**Comment by Jasha10** [comment]
Got it. I'll modify the CI config file to update the Java version.

**Review by Jasha10 — APPROVED** [review]

**Review by heyaudace — APPROVED** [review]

**Comment by Jasha10** [comment]
Thanks again @jlopezpena.

**Comment by JeromeLovy** [comment]
Thanks for the upgrade!

Can we expect a new release of `hydra-core` in a near future? That would be lovely.

(My use case: use hydra-core powered [dvc](https://pypi.org/project/dvc/) together with [datacompy](https://pypi.org/project/datacompy/) which requires `antlr` runtime >= 4.11 through `fugue`.

**Comment by Jasha10** [comment]
I'll be happy to do a release but ideally would want to get the CI working first. See https://github.com/facebookresearch/hydra/pull/2909 for current failures related on the Mac CI. If anyone can help debug this, that would be great.

**Comment by DavidePaglieri** [comment]
Hi there, is there any news on this? Having a pip-installable hydra version that supports `antlr` 4.11 would make things a lot easier than having to install it from source.

**Pull request merged**
