### PR TITLE
upgrade to isort 5.5.2

### PR DESCRIPTION
**Pull request by vporta**
## Motivation

To fix issue #751 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan
Run tests as per the contributing documentation. 
```
$ nox -s lint
$ FIX=1 nox -s lint_plugins
$ pytest
```
## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)
Issue #751

### CODE REVIEW

**Comment by omry** [comment]
Many errors are unrelated, please rebase.

**Comment by omry** [comment]
Please fix your diff to include only your changes. (you merged in some stuff from master). don't merge, rebase.

**Comment by omry** [comment]
are the tests passing locally when you run them with nox?

**Comment by vporta** [comment]
> are the tests passing locally when you run them with nox?

They were passing earlier before I opened the PR. I think I mistakenly added the wrong `upstream` source. Fixed it now.

> Please fix your diff to include only your changes. (you merged in some stuff from master). don't merge, rebase.
On my branch `isort==5.5.2`: `$ git rebase upstream/isort==5.5.2` right? I am running the tests. If they pass I'll push. 

Thanks.

**Comment by omry** [comment]
I am actually not sure of the exact command from a fork, sorry.
If you really get stuck you can just create a new branch and copy things over.

**Comment by vporta** [comment]
> I am actually not sure of the exact command from a fork, sorry.
> If you really get stuck you can just create a new branch and copy things over.

I created a new branch and tests are passing. I'll open a new PR?

**Comment by omry** [comment]
Yup, open a new one and close this one.

**Pull request closed without merging**
