### PR TITLE
Synch grammar documentation with current implementation

### PR DESCRIPTION
**Pull request by odelalleau**
This was overlooked in #1599

Marking it as draft for now because I'm not sure about two points:

1. Should I manually edit the versioned 1.1 version of the doc as well? (or is there an automatic way to synch it?)
2. Should this PR be merged in master, 1.1_dev_branch, or both?

### CODE REVIEW

**Comment by omry** [comment]
1. Yes, edit the 1.1 version in the doc as well as the main version (which you already did).
2. No, no need to edit int the branch. master is enough (website is built from master).

**Comment by odelalleau** [comment]
> 1. Yes, edit the 1.1 version in the doc as well as the main version (which you already did).
> 2. No, no need to edit int the branch. master is enough (website is built from master).

Perfect, thanks! Should be good now :)

**Review by omry — APPROVED** [review]
lgtm!

**Comment by odelalleau** [comment]
I merged in spite of the (unrelated) CI failures

**Pull request merged**
