### PR TITLE
Create pythonpublish.yml

### PR DESCRIPTION
**Pull request by projectghostshell**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes/No

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by projectghostshell** [comment]
> ## Motivation
> (Write your motivation for proposed changes here.)
> 
> ### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?
> Yes/No
> 
> ## Test Plan
> (How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)
> 
> ## Related Issues and PRs
> (Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

yes im

**Comment by omry** [comment]
Thanks.
can you provide context how this is used?

**Comment by projectghostshell** [comment]
Still in progress 

Louis Lee

**Comment by omry** [comment]
What is in progress?
Also, while I appreciate the PR - I am not quiet sure what is your motivation for providing it.

**Comment by projectghostshell** [comment]
I need explore and get more understanding about hydra..^^ but no worries no harm or illegal wor/used on it 


Louis Lee

**Comment by omry** [comment]
I am not worried, the PR seems fine.
I am just trying to understand why you sent it.
Are you planing on triggering the github action flow for publishing the package or is this for me to use?

**Comment by projectghostshell** [comment]
Both also can 

Louis Lee

**Comment by omry** [comment]
Louis Lee, I am closing this:
Please open individual pull requests or GitHub issues problems, and answer the relevant questions, especially what the issue that are solving is.

Thanks for understanding.

**Pull request closed without merging**
