### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by paantya**
Installation conda: `conda install -c conda-forge hydra-core`

## Motivation
could be installed using conda and there was no need to look separately how to do it.

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan
run in terminal: `conda install -c conda-forge hydra-core`

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs
No
(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by paantya** [comment]
i do it!

image

**Comment by jieru-hu** [comment]
thanks for you PR!

I think this might be a better place for it 
https://github.com/facebookresearch/hydra/blob/master/website/versioned_docs/version-1.0/intro.md#installation

Since it looks like only hydra-core 1.0 is available.

**Comment by omry** [comment]
As I am not directly maintaining the conda installation (and it often lag for many months behind the pip package), I would rather not document it here.

Thanks for understanding.

**Comment by paantya** [comment]
@omry @jieru-hu 
Let's write that the version will not be the latest in head github link project

**Comment by omry** [comment]
@paantya:
I would like to encourage people to install with pip to ensure they are using the latest version.
Since you can pip install inside conda anyway, I think this is not worth the extra confusion.

**Pull request closed without merging**
