### PR TITLE
Update nevergrad default optim to NGOpt

### PR DESCRIPTION
**Pull request by jrapin**
## Motivation

`NGOpt` is the best algorithm overall, it adapts to the current settings.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)
N/A

## Related Issues and PRs

N/A
(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by jrapin** [comment]
@omry initially I was also planning to add a way to catch jobs errors and send infinity in that case instead of raising (if it does not happen on all jobs). Is there a way to make something like this work?

**Comment by omry** [comment]
1. Please add a news fragment in the news directory inside the plugin.
2. Not currently, this would require a change in all launchers. It does make sense to support partial failure though, can you file a separate enhancement request?

**Review by omry — CHANGES_REQUESTED** [review]
This is an important change. can you add a news fragment file?

**Review by omry — APPROVED** [review]

**Comment by omry** [comment]
Thanks @jrapin.
Do you want a new version released as well or can this wait for something more significant to come along?

**Comment by jrapin** [comment]
> Thanks @jrapin.
> Do you want a new version released as well or can this wait for something more significant to come along?

Up to you. I'd say it's probably significant enough (NGOpt is supposed to be significantly better than OnePlusOne), but there is no hurry anyway (and my biggest concern was the documentation, which is fixed)

**Comment by omry** [comment]
I can give you release access to the plugin.
@shagunsodhani, do you mind documenting the current plugin release process (with towncrier news update)?

**Comment by jrapin** [comment]
> I can give you release access to the plugin.
> @shagunsodhani, do you mind documenting the current plugin release process (with towncrier news update)?

Could be useful indeed, although I would not push without your go (except emergency, which I don't expect to happen :D)
And indeed, I'd need to know how you do the releases

**Comment by omry** [comment]
Invited you as a maintainer to https://pypi.org/project/hydra-nevergrad-sweeper/

I also invited you and @gwenzek as maintainers to the submitit plugin.

**Pull request merged**
