### PR TITLE
Support Python 3.10

### PR DESCRIPTION
**Pull request by Jasha10**
To work around issue #2181, this PR is based on a branch of the hydra repo (not based on a fork).
Supersedes PR #2166.

### CODE REVIEW

**Comment by Jasha10** [comment]
From the circleci "trigger_plugin_pipelines" job:
```
AssertionError: Unexpected response while submitting CIRCLECI job for plugins. Response: {'message': 'Project not found'}
```

**Comment by Jasha10** [comment]
All plugin CI jobs are enabled for Python3.10 except for the nevergrad sweeper tests.

**Review by jieru-hu — APPROVED** [review]
👍 🎉

**Review by pixelb — APPROVED** [review]
fantastic!

**Pull request merged**
