### PR TITLE
Add torchrun launcher plugin

### LINKED ISSUE #2038: [Feature Request] hydra with torch.distributed.launch
# 🚀 Feature Request

## Motivation

I want to use hydra with `torch.distributed.launch` for multi-node multi-GPU training. The problem is the `torch.distributed.launch` module will automatically pass a `local_rank` argument to the script thus leading to `unrecognized arguments: --local_rank`. 
In this case, how should I program my customized file accordingly to accept this appended argument?
Currently, it seems command arguments in the format of `--some_argument` will be directly received by hydra.

### PR DESCRIPTION
**Pull request by jbaczek**
## Motivation

PyTorch distributed apps is a common use case for hydra (according to many github issues). Currently implementation of `torchrun` interferes with hydra in a way, that causes hydra to initialize multiple times, leading to many race conditions. \
This PR contains a launcher plugin that fixes the issue, forking the process after hydra is initialized.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes
This MR is submitted on behalf of NVIDIA.

## Test Plan

Use machine with multiple GPUs. \
Use [pytorch docker conrainer](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) or install PyTorch in any other way. \
Install plugin with `pip`.  \
How to run `torch distributed` without plugin:
```bash
torchrun --nproc_per_node=8 my_app.py
```
How to run with plugin:
```bash
python my_app.py -m hydra/launcher=torchrun hydra.launcher.nproc_per_node=8
```

## Related Issues and PRs

Resolves https://github.com/facebookresearch/hydra/issues/2038

### CODE REVIEW

**Comment by jbaczek** [comment]
Should I lint it? Or will you do this on your side?

**Comment by jieru-hu** [comment]
hi @jbaczek  - thanks very much for your contribution! 

We've created  [`contrib`](https://github.com/facebookresearch/hydra/tree/main/contrib) here for plugin contributions. We've also included a `README` there.  
Could you update this PR and move this plugin to the `contrib` folder and add integration tests? 

pls let us know if you have any question on this. thanks again.

**Comment by jbaczek** [comment]
@jieru-hu I've moved the plugin to the `contrib` dir and added the tests. Do you need me to do something more?

**Comment by jieru-hu** [comment]
thanks @jbaczek  and sorry for the late response. I will take a look at this

**Comment by jieru-hu** [comment]
looks great, thanks for your contribution @jbaczek !

**Comment by omry** [comment]
Thanks again for contributing this launcher. At the time, Hydra maintainers asked you to place it under `contrib` as part of an experiment in hosting community plugins. That was not the structure you originally proposed, and I appreciate that you accommodated the request.

After reviewing the result, I do not think the `contrib` model is sustainable. The plugin is hosted in the Hydra repository but is not covered by CI, released, or actively maintained. Its location nevertheless creates an expectation that Hydra owns and supports it.

I am therefore going to remove the Torchrun launcher from `contrib` and retire the policy of hosting third-party plugins there. This is not a negative judgment on the contribution—it addressed a real problem and provided the basis for subsequent external work.

If you are interested, you are welcome to host and maintain the launcher in your own repository. I would also be open to hosting documentation for an externally maintained Torchrun launcher in Hydra’s plugin documentation, if you would like to contribute that documentation.

Thank you again for contributing it.

**Pull request merged**
