### PR TITLE
Update Simple Launcher Example for Docker

### PR DESCRIPTION
**Pull request by scottilee**
## Motivation

Addresses #841 for the ray launcher example.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

WIP

## Related Issues and PRs

#841

### CODE REVIEW

**Comment by jieru-hu** [comment]
Thanks for the PR @scottilee! I think we had some miscommunication in #841  (sorry for the confusion!)

We want an example that we can run locally and launch the example app on AWS in a docker container - which is different from what you have here. Basically, from our local machine, we want to run something like
```
python myapp.py hydra/launcher=ray_aws hydra.launcher.ray.run_env=docker
```
and then launch the example app on AWS. 

Happy to provide more context if needed, feel free to join our [chat](https://hydra-framework.zulipchat.com/login/) if you want, it might be easier that way :)

**Review by jieru-hu — CHANGES_REQUESTED** [review]
Back to you queue for now  @scottilee :)

**Comment by omry** [comment]
Hi @scottilee, are you planning to complete the work on this?

**Comment by scottilee** [comment]
@omry taking a look now.

**Pull request closed without merging**
