### PR TITLE
Update Ray AMI

### PR DESCRIPTION
**Pull request by jieru-hu**
python 3.8.10 is out, need to update the test AMI.

### CODE REVIEW

**Comment by omry** [comment]
Thanks.
Is the process for this documented?
1. How do you know you need to update the AMI?
2. How do you update the AMI?

**Comment by jieru-hu** [comment]
> Thanks.
> Is the process for this documented?
> 

> 1. How do you know you need to update the AMI?

The Exception complains that python version does not match (3.8.10 != 3.6.6), which means we do not have conda env available with this version, as a result, the test fall back on the base conda env.  (I will update the message to make it more clear. )

> 2. How do you update the AMI?

I used the script here  to build the AMI https://github.com/facebookresearch/hydra/tree/master/plugins/hydra_ray_launcher/integration_test_tools

I'm going to add a readme file in this folder (for the process.)


I've tracked these in #1602

**Comment by omry** [comment]
What changed and caused the old AMI to break?

**Comment by jieru-hu** [comment]
> What changed and caused the old AMI to break?

a new python version :(  (3.8.10) - we pre-installed all python version's conda env on the AMI - since 3.8.10 is recently released, it was not availabe on the AMI.

**Comment by omry** [comment]
> and we need the two python versions to be the same for cloudpickle.

Can you provide more context on this? Is this restriction documented anywhere in cloudpickle?
I would expect cloudpickle to not be sensitive to minor Python version differences.

**Comment by jieru-hu** [comment]
> > and we need the two python versions to be the same for cloudpickle.
> 
> Can you provide more context on this? Is this restriction documented anywhere in cloudpickle?
> I would expect cloudpickle to not be sensitive to minor Python version differences.

on their github they only say `Cloudpickle can only be used to send objects between the *exact same version of Python.*`. 
I think I ran into some issue with running on differnt python micro versions when I was working on the tests but I'm not 100%. I will look into  relaxing the version requirements to minor version only.

**Comment by omry** [comment]
So yeah, I think it will help to pin our circleci images to something very specific as long as we are willing to update it from time to time.

**Pull request merged**
