### PR TITLE
skip shell completion integration tests if expect is not installed

### PR DESCRIPTION
**Pull request by omry**
cc @andrewnaguib

### CODE REVIEW

**Comment by andrewnaguib** [comment]
Haha, I was about to prepare a PR for that. Thanks!

**Comment by omry** [comment]
Hehe.
Btw, are you going to give the zsh completion plugin a try?

**Comment by andrewnaguib** [comment]
Definitely, I was a bit busy lately. I should be submitting the draft soon (within the next three days) to discuss it together.

**Comment by omry** [comment]
awesome!

**Pull request merged**
