### PR TITLE
add task_function kwarg to on_job_start callback

### PR DESCRIPTION
**Pull request by Jasha10**
This PR closes feature request #2352 opened by @jgbos, adding a `task_function` keyword argument to the `on_job_start` callback.

TODO:
- [X] add test

### CODE REVIEW

**Review by pixelb — APPROVED** [review]
This looks useful and should be backwards compat with older callers.
Approving assuming tests

**Comment by Jasha10** [comment]
I've added a test to confirm that the updated callback API works as expected.
That being said, pickling the `task_function` doesn't work.
The problem is that the `@hydra.main` decorator wraps the `task_function` (à la `functools.wraps`), which makes pickling fail.
When I add the line `pickle.dumps(task_function)` to the `on_job_start` method in the test code, a `PicklingError` occurs.

Steps to reproduce:
1. check out this PR branch and install hydra:
```text
git clone -b possible-improvement-to-rerun https://github.com/Jasha10/hydra jasha10_hydra
cd jasha10_hydra
pip install -e .
```
2. modify the file `tests/test_apps/app_with_callbacks/on_job_start_accepts_task_function/my_app.py` so that the `on_job_start` method calls `pickle.dumps` on the `task_function`:
```python
$ cat tests/test_apps/app_with_callbacks/on_job_start_accepts_task_function/my_app.py
...

class OnJobStartCallback(Callback):
    def on_job_start(
        self, config: DictConfig, *, task_function: TaskFunction, **kwargs: Any
    ) -> None:
        import pickle
        pickle.dumps(task_function)

...
```
3. run the test app:
```text
$ python tests/test_apps/app_with_callbacks/on_job_start_accepts_task_function/my_app.py
/Users/jasha10/dev/foo/jasha10_hydra/hydra/_internal/callbacks.py:28: UserWarning: Callback OnJobStartCallback.on_job_start raised PicklingError: Can't pickle <function my_app at 0x10853eaf0>: it's not the same object as __main__.my_app
  warnings.warn(
```

This is the same problem mentioned in [this comment](https://github.com/facebookresearch/hydra/issues/2038#issuecomment-1063935678) on the `torch.distributed.launch` feature request.
@jgbos, what do you think?

**Comment by jgbos** [comment]
@Jasha10 thanks for starting this PR.  This might be a bigger challenge.  Before I went on vacation last week I got a callback implementation running but I had to do two things:

- Use `cloudpickle` instead of `pickle`
- Make sure the task function is in a loadable package (i.e., not in `__main__`)

So I know this is possible, though I'm not sure how you should proceed with testing.  I know the `submitit` team successfully pickles task functions, I'll go dig through their code.

**Comment by Jasha10** [comment]
> So I know this is possible

Got it. So in your assessment, will this PR still be useful in its current form?

**Comment by jgbos** [comment]
> Got it. So in your assessment, will this PR still be useful in its current form?

Yep.  The challenge is on the user end I've successfully implemented this.

**Pull request merged**
