### PR TITLE
cache only the downloaded bottles in ~/Library/Caches/Homebrew instead

### PR DESCRIPTION
**Pull request by jieru-hu**
## Motivation

We've been experiencing a lot of macos tests failures with brew, which seems might be related with caching
```
#!/bin/bash --login -eo pipefailbrew updatebrew upgrade gitbrew install fish
Connection to github.com closed by remote host.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash pop'
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions && git stash pop'
Updated 3 taps (homebrew/cask-versions, homebrew/cask and adoptopenjdk/openjdk).
```

I reached out to circleCI support and they suggested that we should only cache the downloaded bottles.

Response from them below:

> 
>I have experienced slow pulls from homebrew-core repository recently and it could be related.
> Also, you are seeing these Homebrew messages, because you are caching the Homebrew metadata, and doing this also could lead to many problems.
> I advice you to cache only the downloaded bottles in ~/Library/Caches/Homebrew instead. It will only take a few seconds to install.
> 
>       - run:
>           name: Preparing environment - Brew
>           command: |
>             brew update
>             brew upgrade git
>             brew install fish
>             brew cleanup # Optional step: cleanup old bottles
>       - save_cache:
>             paths: ~/Library/Caches/Homebrew
> 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes/No

## Test Plan

CI should pass.

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by jieru-hu** [comment]
Well, same issues still occurs https://app.circleci.com/pipelines/github/jieru-hu/hydra/590/workflows/3eb9766e-734e-4dfe-9fed-d5002fc905eb/jobs/6418
Even with no caching :( 
Seems like a brew issue then.

**Comment by jieru-hu** [comment]
open issue with brew https://github.com/Homebrew/homebrew-core/issues/61772

I think it's still worth to land this PR though. so i'm keeping it open :)

**Comment by omry** [comment]
CI is failign due to something with Ax, can you take a look?

**Comment by jieru-hu** [comment]
> CI is failign due to something with Ax, can you take a look?

yea I was planning on following up on that today, but saw that you got it resolved in a separate thread :)

**Pull request merged**
