### PR TITLE
[configen] Handle `typing.Callable` types

### LINKED ISSUE #1299: [Bug] Configen does not support `Callable` types
# 🐛 Bug
## Description

When attempting to use configen to generate a [`Callable`](https://docs.python.org/3/library/typing.html#typing.Callable) type, a `TypeError` is thrown [here](https://github.com/facebookresearch/hydra/blob/dbe1e6882386fd1c1b721992542844e58bf0722a/tools/configen/configen/configen.py#L118).

See example config below.

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
configen --config-dir conf --config-name pytorch_lightning
```

Example config from lightning

```yaml
# pytorch_lightning.yaml
defaults:
  - configen_schema

configen:
    output_dir: ${hydra:runtime.cwd}

    header: |
        # Autogenerated by configen, do not edit.
        # If encountering an error, please file an issue @
        # https://github.com/romesco/hydra-lightning
        # fmt: off
        # isort: skip_file
        # flake8: noqa
        # Hydra + Lightning

    module_path_pattern: 'hydra_configs/{{module_path}}.py'

    modules:
        - name: pytorch_lightning.metrics.classification
          classes:
            - Accuracy
            - Fbeta
            - Precision
```

** Stack trace/error message **

```sh
Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 364, in _run_hydra
    run_and_report(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 215, in run_and_report
    raise ex
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    lambda: hydra.run(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 109, in run
    return run_job(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 263, in main
    code = generate_module(cfg=cfg.configen, module=module)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 182, in generate_module
    not missing_annotation_type and is_incompatible(type_)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 118, in is_incompatible
    if type_ is Any or issubclass(type_, (int, float, str, bool, Enum)):
TypeError: issubclass() arg 1 must be a class
python-BaseException
```

## Expected Behavior

Config should be generated normally

## System information
- **Hydra Version** :  1.1.0dev5
- **Python version** : 3.8
- **Virtual environment type and version** : virtualenv
- **Operating system** : Ubuntu 20.04

## Additional context

If I attempt to wrap the failing `if` statement with a try catch like below, I get another error [here](https://github.com/facebookresearch/hydra/blob/dbe1e6882386fd1c1b721992542844e58bf0722a/tools/configen/configen/utils.py#L87)

```python
    try:
        if type_ is Any or issubclass(type_, (int, float, str, bool, Enum)):
            return False
    except TypeError:
        return False
```

And so I wrapped that failing block with another try/catch:

```
                try:
                    classname = t.__name__
                except AttributeError:
                    classname = t._name
```

And now configen works.

This is a hacky approach IMO, and a better solution could be proposed.

I'm not too familiar with the internals of configen, so I don't know what the best way is to check for subclasses or check for names. (Maybe there are other helper methods somewhere?)

I can open a PR if this is fine.

### PR DESCRIPTION
**Pull request by piraka9011**
## Motivation

Attempt to resolve #1299.
I'm unsure if this is the best path forward, so looking for feed back on the approach.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

Not sure where to test this but I am also assuming `Callable` or similar types _will not_ be supported (or should they)?

## Related Issues and PRs

#1299

### CODE REVIEW

**Comment by piraka9011** [comment]
cc: @romesco

**Review by omry — COMMENTED** [review]
1. The two fixes are rather hacky, I would prefer not to rely on the exception to infer what the types are.

2. Please add appropriate tests, see the other tests.

Once you have tests, it will be easier for me to suggest a cleaner implementation.

**Comment by OregonSells** [comment]
Can I trying?

**Comment by piraka9011** [comment]
I still don't think my original question was answered.
Does Hydra/configen support all the types in the `typing` module, or are/should some be excluded for... reasons (Maybe b/c Omegaconf doesn't support it)?

Given that info, I think a better approach can be proposed.

**Comment by omry** [comment]
Configen is a tool to generate configs that should be used with Hydra and OmegaConf.
It does not support anything not supported by OmegaConf.
In particular, the solution for unsupported fields is to mark them as Any and pass them as a passthrough (`instantiate(cfg.foo, a_callable=my_function`).

This is similar to how the Optimizer params field is handled.

**Comment by piraka9011** [comment]
> It does not support anything not supported by OmegaConf.

Thanks for the clarification!

**Review by omry — CHANGES_REQUESTED** [review]
Marking as "request changes" to take this off my queue until you add the tests.

**Comment by omry** [comment]
@piraka9011, any plans to complete this?

**Comment by piraka9011** [comment]
I haven't had time to look into this further but will post any findings/updates if I get the chance.

**Comment by omry** [comment]
Okay.
FYI: without testing I will reject this PR within a few weeks.

**Comment by omry** [comment]
Feel free to submit again if you can add the requested tests.

**Pull request closed without merging**
