### PR TITLE
Copy changes in submitit plugin from master

### PR DESCRIPTION
**Pull request by shagunsodhani**
## Motivation

Copy changes in submitit plugin from master

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

CI

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Review by omry — APPROVED** [review]

**Comment by omry** [comment]
can you retry the failed windows jobs?

**Comment by shagunsodhani** [comment]
Retrying via ci website

**Comment by shagunsodhani** [comment]
Still seeing timeouts :(

**Comment by shagunsodhani** [comment]
Should I land these changes or wait for the CI issue to be resolved?

**Comment by jieru-hu** [comment]
I kicked off the failed runs and now they are all passing.

I'm still working on figure out the root cause/and fix for win issue :)

**Pull request merged**
