### PR TITLE
Fix indentation of yaml data on docs

### PR DESCRIPTION
**Pull request by harupy**
## Motivation

Fix indentation of yaml data on docs.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by omry** [comment]
Awesome, did you test what it looks like by running a local Docusaurus instance? (as documented in the README at the root of the website dir?

**Comment by harupy** [comment]
@omry I just did.

before
Screen Shot 2020-02-12 at 2 00 17


after
Screen Shot 2020-02-12 at 2 00 24

**Comment by omry** [comment]
Once #413 lands please rebase on top, it should fix the CI issues.

**Comment by omry** [comment]
#413 will fix CI in your other PRs as well. rebase them all on top.

**Comment by omry** [comment]
Please rebase your outstanding diffs, tests should pass on master now.

**Comment by omry** [comment]
Thanks for taking the time to fix this!

**Pull request merged**
