### PR TITLE
Add GridSampler to Optuna Sweeper

### PR DESCRIPTION
**Pull request by beerzyp**
### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Related Issues and PRs

Add GridSampler support, issue https://github.com/facebookresearch/hydra/issues/1815.

### CODE REVIEW

**Comment by Jasha10** [comment]
@beerzyp thanks very much for the PR, we will review it shortly :)

**Comment by jieru-hu** [comment]
thanks @beerzyp  for the PR.

I assume you are following my recommendation in #1815 - in which I didn't lay out everything that needs to be changed. I should have put more details there. sorry.

1. the change doesn't actually run - if you try to run an application with sampler=grid, you'd see
```
  File "/Users/jieru/workspace/hydra-fork/hydra/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
TypeError: Error instantiating 'optuna.samplers._grid.GridSampler' : __init__() got an unexpected keyword argument 'seed'
```
the reason being GridSamplerConfig cannot extend SamplerConfig - it does not accept a `seed` param.

2. GridSampler fits a bit awkwardly with the Optuna config: 1) it expects a `search_space` param to be passed in to the init the class. 2) Optuna already has a `hydra.sweeper.search_space` config available. 

A bit more context on how the Optuna sweeper works:
the Optuna config has [custom logic](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py#L35-L60) parsing `hydra.sweeper.search_space`. To support `GridSampler`, I think we will need some custom logic in the Optuna sweeper to check if the Sampler is a GridSampler and if so, override the search_space params accordingly. If we directly pass a list of params to the Sampler like how it is implemented now, we actually miss out all the power Hydra's [override syntax](https://hydra.cc/docs/advanced/override_grammar/basic) provides and the behavior doesn't align well with the Optuna sweeper's current user experience. 

While GridSampler is not supported yet, Hydra's BasicSweeper actually provides a grid search out of the box, here is the doc
https://hydra.cc/docs/advanced/override_grammar/extended#sweeps
https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run

**Review by jieru-hu — CHANGES_REQUESTED** [review]
see my comment.

**Comment by cschell** [comment]
@jieru-hu, I have a question about that statement

> While GridSampler is not supported yet, Hydra's BasicSweeper actually provides a grid search out of the box

This is not true for distributed scenarios, right? So, for example, I run multiple optuna-sweeper instances within Kubernetes jobs, all instances coordinated by a central optuna-RDBStorage. If I understand this correctly, I have no way to coordinate the hyperparameter-runs when I use the basic hydra sweeper, right?

**Comment by jieru-hu** [comment]
@cschell sorry I just saw your comment! Yes, you are right - I didn't consider the Distributed scenarios in this case. thanks for pointing that out!

**Comment by jieru-hu** [comment]
closing due to inactivity. we are going to support this in the upcoming release.

**Pull request closed without merging**
