### PR TITLE
fix filehandler of colorlog will change the output directory of log file

### PR DESCRIPTION
**Pull request by AlsonYang**
This is to fix the issue #2662

### CODE REVIEW

**Review by Jasha10 — APPROVED** [review]
Looks good to me.

The updated filename is the same filename that's used in https://github.com/facebookresearch/hydra/blob/71ca75b2184a60161730eb857c592ff62eba7ece/hydra/conf/hydra/job_logging/default.yaml.

Thanks @AlsonYang.

**Comment by AlsonYang** [comment]
> Looks good to me.
> 
> The updated filename is the same filename that's used in [hydra/conf/hydra/job_logging/default.yaml](https://github.com/facebookresearch/hydra/blob/71ca75b2184a60161730eb857c592ff62eba7ece/hydra/conf/hydra/job_logging/default.yaml).
> 
> Thanks @AlsonYang.

Hi @Jasha10, thanks for approving the change! 

I haven't had experience contributing to an open source project. I have got a couple of questions hoping you could clarify.
1. Is there extra action needs to be taken on my side for this to be merged and released? 
2. Once it is merged, how do I find out which release will incorporate this fix so that I can pip update the package after the release is out?

**Comment by omry** [comment]
Can you add a news fragment [here](https://github.com/facebookresearch/hydra/tree/main/plugins/hydra_colorlog/news) ?

**Comment by AlsonYang** [comment]
> Can you add a news fragment [here](https://github.com/facebookresearch/hydra/tree/main/plugins/hydra_colorlog/news) ?

@omry added.

**Comment by Jasha10** [comment]
> Hi @Jasha10, thanks for approving the change!
> 
> I haven't had experience contributing to an open source project. I have got a couple of questions hoping you could clarify.
> 
> 1. Is there extra action needs to be taken on my side for this to be merged and released?
> 2. Once it is merged, how do I find out which release will incorporate this fix so that I can pip update the package after the release is out?

@AlsonYang I'm happy to answer your questions, and sorry for my slow reply.

1. No further action is required on your part at this time. A current maintainer of the project, i.e. someone with write permissions on this repository, will need to take action to merge this PR. If they want to voice any questions or concerns before merging, they'd likely do so by commenting on this PR.
2. If/when these changes are merged, they'd be incorporated into the `main` branch of this repository. The maintainer would then need to package and release a new version of the `hydra-colorlog` package so that these changes will be visible on pypi. Sorry I can't give you a timeframe for when that would happen as I'm no longer involved in this project in an official capacity. (I was a maintainer of Hydra in the past, and I left my review above as informational/advisory for future maintainers.)

If you want to incorporate this PR's changes in your own work and don't want to wait for an official release, my advice would be to pip-install from your fork instead of pip-installing the version that's hosted on PyPi:
```bash
pip install 'git+https://github.com/AlsonYang/hydra/@fix/colorlog_filehandler#egg=hydra-colorlog&subdirectory=plugins/hydra_colorlog'
```
This will install the `hydra-colorlog` package from the `fix/colorlog_filehandler` branch of your fork.
Alternatively, you could do an editable install from your local clone of Hydra:
```bash
pip install --editable ~/dev/my_local_clone_of_hydra/plugins/hydra_colorlog
```

**Review by omry — APPROVED** [review]

**Comment by AlsonYang** [comment]
> > Hi @Jasha10, thanks for approving the change!
> > 
> > I haven't had experience contributing to an open source project. I have got a couple of questions hoping you could clarify.
> > 
> > 1. Is there extra action needs to be taken on my side for this to be merged and released?
> > 2. Once it is merged, how do I find out which release will incorporate this fix so that I can pip update the package after the release is out?
> 
> @AlsonYang I'm happy to answer your questions, and sorry for my slow reply.
> 
> 1. No further action is required on your part at this time. A current maintainer of the project, i.e. someone with write permissions on this repository, will need to take action to merge this PR. If they want to voice any questions or concerns before merging, they'd likely do so by commenting on this PR.
> 2. If/when these changes are merged, they'd be incorporated into the `main` branch of this repository. The maintainer would then need to package and release a new version of the `hydra-colorlog` package so that these changes will be visible on pypi. Sorry I can't give you a timeframe for when that would happen as I'm no longer involved in this project in an official capacity. (I was a maintainer of Hydra in the past, and I left my approval above as informational/advisory for future maintainers.)
> 
> If you want to incorporate this PR's changes in your own work and don't want to wait for an official release, my advice would be to pip-install from your fork instead of pip-installing the version that's hosted on PyPi:
> ```bash
> pip install 'git+https://github.com/AlsonYang/hydra/@fix/colorlog_filehandler#egg=hydra-colorlog&subdirectory=plugins/hydra_colorlog'
> ```
> This will install the `hydra-colorlog` package from the `fix/colorlog_filehandler` branch of your fork.
> Alternatively, you could do an editable install from your local clone of Hydra:
> ```bash
> pip install --editable ~/dev/my_local_clone_of_hydra/plugins/hydra_colorlog
> ```

@Jasha10 Thanks for answering my question. This is super super helpful, really appreciate it!

**Pull request merged**
